# =============================================================================
# Externals.cmake -- every third-party dependency, as a real CMake target.
#
# All of them come from external/ and nowhere else: no vendored copies under
# src/, no pre-built archives, no system include paths. external/README.md
# lists what belongs there and where each library comes from; this file turns
# those directories into targets and fails at configure time, by name, if one
# is missing.
#
# Targets defined here
# --------------------
#   ext::json       header-only  nlohmann/json                 (struct templates)
#   ext::stb        header-only  stb_image / stb_vorbis        (image, ogg)
#   ext::drlibs     header-only  dr_mp3 / dr_wav / dr_flac     (audio)
#   ext::glm        header-only  glm                           (cloth solver maths)
#   ext::bink2      header-only  Bink 2.7d ABI headers         (video)
#   ext::jpegturbo  static       libjpeg-turbo 3.2.0           (JPEG)
#   ext::webp       static       libwebp 1.6.0 decoder         (WebP)
#   ext::sqlite     static       SQLite amalgamation           (the dat index)
#   ext::xatlas     static       xatlas UV atlas generator     (glTF atlas bake)
# =============================================================================

set(CASTLEMIST_EXTERNAL_DIR "${PROJECT_SOURCE_DIR}/external"
    CACHE PATH "Root of the third-party library checkout")
get_filename_component(CASTLEMIST_EXTERNAL_DIR "${CASTLEMIST_EXTERNAL_DIR}" ABSOLUTE)
set(_ext "${CASTLEMIST_EXTERNAL_DIR}")

message(STATUS "castlemist: externals    = ${_ext}")

# Fail early and by name rather than with a wall of "no such file" later.
function(_castlemist_require path what)
    if (NOT EXISTS "${path}")
        message(FATAL_ERROR
            "Missing dependency '${what}':\n  ${path}\n"
            "See external/README.md for what belongs in ${CASTLEMIST_EXTERNAL_DIR}.")
    endif()
endfunction()

# Declares a header-only dependency as ext::<name>, checking one witness file.
function(_castlemist_header_lib name dir witness)
    _castlemist_require("${_ext}/${dir}/${witness}" "${name}")
    add_library(ext_${name} INTERFACE)
    target_include_directories(ext_${name} INTERFACE "${_ext}/${dir}")
    add_library(ext::${name} ALIAS ext_${name})
endfunction()

# --------------------------------------------------------- header-only libs --

_castlemist_header_lib(json   "nlohmann-json/single_include" "nlohmann/json.hpp")
_castlemist_header_lib(stb    "stb-master"                   "stb_image.h")
_castlemist_header_lib(drlibs "dr_libs-master"               "dr_mp3.h")
_castlemist_header_lib(glm    "glm-1.0.3"                    "glm/glm.hpp")

# Bink stays pinned to 2.7d ON PURPOSE. castlemist drives Guild Wars 2's own
# bink2w64.dll (2.7p) through GetProcAddress, and that DLL's ABI matches the
# 2.7d headers -- the newer SDK in external/bink2 does NOT. The 2.7d pair is
# the one part of external/ that is tracked in git; see its README.
_castlemist_header_lib(bink2  "bink2-2.7d"                   "bink_2_7d.h")

# ------------------------------------------------------------------- SQLite --
#
# The amalgamation, compiled here rather than linked from the system, so that
# the indexer in tools/ and the reader in src/db can never disagree about which
# SQLite produced dumps/index/gw2_index.db.

_castlemist_require("${_ext}/sqlite3/sqlite3.c" "sqlite3 amalgamation")
add_library(ext_sqlite STATIC "${_ext}/sqlite3/sqlite3.c")
target_include_directories(ext_sqlite PUBLIC "${_ext}/sqlite3")
target_compile_definitions(ext_sqlite PRIVATE
    SQLITE_THREADSAFE=1
    SQLITE_OMIT_LOAD_EXTENSION=1
    SQLITE_DQS=0)
set_target_properties(ext_sqlite PROPERTIES C_STANDARD 11 POSITION_INDEPENDENT_CODE ON)
add_library(ext::sqlite ALIAS ext_sqlite)

# ------------------------------------------------------- libjpeg-turbo 3.2.0 --
#
# 3.x dispatches sample precision at RUNTIME, so the 8-bit core references
# j12init_*/j16init_*: every file under src/wrapper (bar the generator
# template) has to be compiled or the link fails on those. src/jstdhuff.c is
# include-only and must be left out.

set(_jpeg_root "${_ext}/libjpeg-turbo-3.2.0")
_castlemist_require("${_jpeg_root}/src/jpeglib.h" "libjpeg-turbo")

set(_jpeg_core
    jaricom jcapimin jcarith jchuff jcicc jcinit jclhuff jcmarker jcmaster
    jcomapi jcparam jcphuff jctrans jdapimin jdarith jdatadst jdatasrc
    jdhuff jdicc jdinput jdlhuff jdmarker jdmaster jdphuff jdtrans jerror
    jfdctflt jmemmgr jmemnobs jpeg_nbits)
set(_jpeg_srcs "")
foreach(f ${_jpeg_core})
    list(APPEND _jpeg_srcs "${_jpeg_root}/src/${f}.c")
endforeach()
file(GLOB _jpeg_wrap "${_jpeg_root}/src/wrapper/*.c")
list(FILTER _jpeg_wrap EXCLUDE REGEX "/template\\.c$")
list(APPEND _jpeg_srcs ${_jpeg_wrap})

add_library(ext_jpegturbo STATIC ${_jpeg_srcs})
# jconfig.h / jconfigint.h / jversion.h are generated by upstream's CMake. We
# do not run it, so external/jpegcfg supplies them and must come first.
target_include_directories(ext_jpegturbo PUBLIC
    "${_ext}/jpegcfg"
    "${_jpeg_root}/src")
set_target_properties(ext_jpegturbo PROPERTIES C_STANDARD 11 POSITION_INDEPENDENT_CODE ON)
add_library(ext::jpegturbo ALIAS ext_jpegturbo)

# ------------------------------------------------ libwebp 1.6.0 (decode only) --

set(_webp_root "${_ext}/libwebp-1.6.0")
_castlemist_require("${_webp_root}/src/webp/decode.h" "libwebp")

file(GLOB _webp_srcs
    "${_webp_root}/src/dec/*.c"
    "${_webp_root}/src/dsp/*.c"
    "${_webp_root}/src/utils/*.c"
    "${_webp_root}/src/demux/*.c")
add_library(ext_webp STATIC ${_webp_srcs})
# NB the include root is src/, not src/webp/ -- headers are <webp/decode.h>.
target_include_directories(ext_webp PUBLIC "${_webp_root}" "${_webp_root}/src")
set_target_properties(ext_webp PROPERTIES C_STANDARD 11 POSITION_INDEPENDENT_CODE ON)
add_library(ext::webp ALIAS ext_webp)

# ------------------------------------------------------------------- xatlas --
#
# Generates a fresh, non-overlapping UV atlas from raw mesh geometry -- used to
# bake a GW2 material's real shaded appearance into one self-contained texture
# for materials whose own UVs (a trim sheet, tiled far outside [0,1]) have no
# meaningful "flatten this into one texture" reading of their own.

set(_xatlas_root "${_ext}/xatlas")
_castlemist_require("${_xatlas_root}/xatlas.h" "xatlas")

add_library(ext_xatlas STATIC "${_xatlas_root}/xatlas.cpp")
target_include_directories(ext_xatlas PUBLIC "${_xatlas_root}")
set_target_properties(ext_xatlas PROPERTIES CXX_STANDARD 14 POSITION_INDEPENDENT_CODE ON)
add_library(ext::xatlas ALIAS ext_xatlas)
